source 'https://github.com/CocoaPods/Spec.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SparkDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for SparkDemo 
  pod 'SparkAlgorithm', :path => '../SparkAlgorithm'

end
